// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVFllfHUhHvKxAMepxcA-72zEoFiOITVk',
    appId: '1:628769608440:android:c53d39667b794022cb610d',
    messagingSenderId: '628769608440',
    projectId: 'doorap-350711',
    storageBucket: 'doorap-350711.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3mEpt9qnrllut5BJVWX9hV6T7NiOYhpc',
    appId: '1:628769608440:ios:9f70e86b10df521dcb610d',
    messagingSenderId: '628769608440',
    projectId: 'doorap-350711',
    storageBucket: 'doorap-350711.appspot.com',
    androidClientId: '628769608440-gce7qq0v8qvtuv54ta8obapkj6r019g4.apps.googleusercontent.com',
    iosClientId: '628769608440-q3avl8driasn1pouadfbdvl8l9sj7sf2.apps.googleusercontent.com',
    iosBundleId: 'com.app.doorAp',
  );
}
